name: chatgpt-code-reviewer

on:
  pull_request:

permissions:
  pull-requests: write  # Allows posting review comments
  contents: write       # Often needed if you want to update files, etc.

jobs:
  chatgpt-code-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Review
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
