name: ChatGPT Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering in Actions tab

jobs:
  chatgpt_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # So the workflow can commit changes

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      - name: Run chatgpt.py script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: python Chatgpt.py
