name: chatgpt-code-reviewer
run-name: chatgpt-code-reviewer

on: 
  pull_request:   # triggers on open/synchronize/reopen PRs

jobs:
  chatgpt-code-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Review
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        # Optionally, you can override defaults here:
        # with:
        #   model: gpt-3.5-turbo
        #   max_tokens: 4096
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
