name: Create Index

on:
  workflow_dispatch:

permissions:
  contents: write  # needed to push changes

jobs:
  generate_index_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run create-index.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # optional if you want AI-based descriptions
        run: python scripts/create-index.py

      - name: Commit and Push index.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.md
          git commit -m "Add or update index.md"
          git push
