name: Gather Functions

on:
  workflow_dispatch:

permissions:
  contents: write # needed to push changes back to the repo

jobs:
  gather_functions_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Gather Functions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # optional for AI-based analysis
        run: python scripts/gather-functions.py
      
      - name: Commit repo-function.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add OpenAI/repo-function.md
          git commit -m "Add or update repo-function.md"
          git push

