name: List Repos

on:
  workflow_dispatch:

permissions:
  contents: write  # allows committing/pushing changes to your repo

jobs:
  list_repos_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run list_repos.py script
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: python scripts/list_repos.py

      - name: Commit and push repoList.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add OpenAI/repoList.txt
          git commit -m "Add updated repoList.txt"
          git push
